version: "2"
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
       - "8080:8080" 
       - "50000:50000" 
    volumes:
      - C:/Users/lokeshc2/Desktop/Extras/jenkins:/var/jenkins_home